project:
  type: website
  output-dir: docs



website:
  title: "Kyle Wodehouse"
  description: "Portfolio of Kyle Wodehouse, a chemical engineering student working across polymer science, data analysis, and scientific software."
  google-analytics: "G-E8T39RJ05T"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Projects
        href: projects/proj.qmd
      - blog.qmd
      - text: CV
        href: CV.pdf
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "GitHub"
        href: https://github.com/kylecapybara
      - text: "Contact"
        href: mailto:kwode@udel.edu


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute: 
  freeze: true
