project:
  type: website
  output-dir: docs

website:
  title: "Kyle Wodehouse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Projects
        href: projects/proj.qmd
      - blog.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



